CREATE USER 'zmbdp'@'%' IDENTIFIED BY '123456';
CREATE DATABASE IF NOT EXISTS `spring_oj_dev`;
CREATE DATABASE IF NOT EXISTS `spring_oj_nacos_local`;
CREATE DATABASE IF NOT EXISTS `xxl_job` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT CREATE, DROP, SELECT, INSERT, UPDATE, DELETE, ALTER ON spring_oj_dev.* TO 'zmbdp'@'%';
GRANT CREATE, DROP, SELECT, INSERT, UPDATE, DELETE, ALTER ON spring_oj_nacos_local.* TO 'zmbdp'@'%';
GRANT CREATE, DROP, SELECT, INSERT, UPDATE, DELETE, ALTER ON xxl_job.* TO 'zmbdp'@'%';
